unpublish_node_queue.settings:
  type: config_object
  label: 'Unpublish nodes settings'
  mapping:
    period:
      type: integer
      label: 'Period'
    items_to_create:
      type: integer
      label: 'Items to create'
    disabled:
      type: boolean
      label: 'Disabled'
    unpublsihed_label:
      type: string
      label: 'Unpublished label'
