<?php

/**
 * @file
 * Main file for hooks and custom functions.
 */

use Drupal\Core\StringTranslation\TranslatableMarkup;

/**
 * Implements hook_user_login().
 */

function login_message_user_login($account) {

  $conf = \Drupal::config('login_message.settings');
  $label = $conf->get('message_label');

  $message = new TranslatableMarkup($label . ' <strong>@username</strong>!', [
    '@username' => $account->getDisplayName(),
  ]);
  \Drupal::messenger()->addMessage($message);
}
