<?php

/**
 * @file
 * Custom hooks and functions for module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\my_event\Event\MyEvent;

/**
 * Implements hook_preprocess_HOOK().
 */
function my_event_node_update(EntityInterface $node) {
  // Create event object passing arguments.
  $event = new MyEvent($node);
  /** @var \Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher $dispatcher */
  $dispatcher = \Drupal::service('event_dispatcher');
  // Call it.
  $dispatcher->dispatch(MyEvent::HOOK_NODE_UPDATE, $event);
}

